export default {
    SOME_MUTATION: 'SOME_MUTATION',
    SET_USER: 'SET_USER',
    SET_USER_COURSES: 'SET_USER_COURSES',
    SET_PHOTO_URL: 'SET_PHOTO_URL',
    SET_DISPLAY_NAME: 'SET_DISPLAY_NAME',
    SET_GENDER: 'SET_GENDER',
    SET_BIRTHDAY: 'SET_BIRTHDAY',
    SET_JOB: 'SET_JOB',
    //
    APPEND_ANSWER: 'APPEND_ANSWER',
    //
    APPEND_COURSE: 'APPEND_COURSE',
    //
    SET_TOAST:'SET_TOAST',
    //
    SET_LAYOUT:'SET_LAYOUT',
    //
    APPEND_LESSON:'APPEND_LESSON',
    //
    APPEND_QUESTION:'APPEND_QUESTION',

}
